import { Client, TeamMember, Video, Lead, OnboardingClient, AdCampaign, KBDoc } from "./types";

/* ─── Team ─── */
export const TEAM: TeamMember[] = [
  { id: "e1", name: "Alex", initials: "AL", role: "editor", weeklyVideoCap: 22 },
  { id: "e2", name: "Araceli", initials: "AR", role: "editor", weeklyVideoCap: 22 },
  { id: "e3", name: "Leonardo", initials: "LE", role: "editor", weeklyVideoCap: 22 },
  { id: "e4", name: "Rodrigo", initials: "RO", role: "editor", weeklyVideoCap: 20 },
  { id: "e5", name: "Sergio", initials: "SE", role: "videographer", weeklyVideoCap: 20 },
  { id: "e6", name: "Javier", initials: "JA", role: "editor", weeklyVideoCap: 22 },
  { id: "e7", name: "Santi", initials: "SA", role: "editor", weeklyVideoCap: 22 },
  { id: "sm1", name: "Guido", initials: "GU", role: "social_manager", weeklyVideoCap: 0 },
  { id: "cd1", name: "Jenina", initials: "JE", role: "creative_director", weeklyVideoCap: 0 },
  { id: "a1", name: "Angel", initials: "AN", role: "admin", weeklyVideoCap: 0 },
  { id: "a2", name: "Santiago", initials: "ST", role: "admin", weeklyVideoCap: 0 },
];

export const EDITORS = TEAM.filter((t) => t.role === "editor");
export const WEEKLY_TARGET = 86;

/* ─── Clients (real) ─── */
export const INIT_CLIENTS: Client[] = [
  /* Araceli's clients */
  { id: "c1", name: "Castaways", initials: "CA", monthlyRevenue: 0, assignedEditor: "e2", assignedSocialManager: "sm1", week: 1, status: "active" },
  { id: "c2", name: "Juniors Kenya", initials: "JK", monthlyRevenue: 0, assignedEditor: "e2", assignedSocialManager: "sm1", week: 1, status: "active" },
  { id: "c3", name: "Hicksville", initials: "HI", monthlyRevenue: 0, assignedEditor: "e2", assignedSocialManager: "sm1", week: 2, status: "active" },
  { id: "c4", name: "Pizza Star", initials: "PS", monthlyRevenue: 0, assignedEditor: "e2", assignedSocialManager: "sm1", week: 2, status: "active" },
  { id: "c5", name: "Viva Birria", initials: "VB", monthlyRevenue: 0, assignedEditor: "e2", assignedSocialManager: "sm1", week: 3, status: "active" },
  /* Sergio's clients */
  { id: "c6", name: "Casa Birria", initials: "CB", monthlyRevenue: 0, assignedEditor: "e5", assignedSocialManager: "sm1", week: 1, status: "active" },
  { id: "c7", name: "Silk City", initials: "SC", monthlyRevenue: 0, assignedEditor: "e5", assignedSocialManager: "sm1", week: 1, status: "active" },
  { id: "c8", name: "Kelly's Pub", initials: "KP", monthlyRevenue: 0, assignedEditor: "e5", assignedSocialManager: "sm1", week: 2, status: "active" },
  { id: "c9", name: "Luminere", initials: "LU", monthlyRevenue: 0, assignedEditor: "e5", assignedSocialManager: "sm1", week: 2, status: "active" },
  { id: "c10", name: "Bartending School", initials: "BS", monthlyRevenue: 0, assignedEditor: "e5", assignedSocialManager: "sm1", week: 3, status: "active" },
  { id: "c11", name: "Roosevelt Projects", initials: "RP", monthlyRevenue: 0, assignedEditor: "e5", assignedSocialManager: "sm1", week: 3, status: "active" },
  /* Rodrigo's clients */
  { id: "c12", name: "Supra", initials: "SU", monthlyRevenue: 0, assignedEditor: "e4", assignedSocialManager: "sm1", week: 1, status: "active" },
  { id: "c13", name: "Taco Express", initials: "TE", monthlyRevenue: 0, assignedEditor: "e4", assignedSocialManager: "sm1", week: 2, status: "active" },
  { id: "c14", name: "Nanus", initials: "NA", monthlyRevenue: 0, assignedEditor: "e4", assignedSocialManager: "sm1", week: 2, status: "active" },
  { id: "c15", name: "American Grill", initials: "AG", monthlyRevenue: 0, assignedEditor: "e4", assignedSocialManager: "sm1", week: 3, status: "active" },
  { id: "c16", name: "Slappin", initials: "SL", monthlyRevenue: 0, assignedEditor: "e4", assignedSocialManager: "sm1", week: 3, status: "active" },
  { id: "c17", name: "Lenny's", initials: "LE", monthlyRevenue: 0, assignedEditor: "e4", assignedSocialManager: "sm1", week: 4, status: "active" },
  /* Alex's clients */
  { id: "c18", name: "BAM", initials: "BA", monthlyRevenue: 0, assignedEditor: "e1", assignedSocialManager: "sm1", week: 1, status: "active" },
  { id: "c19", name: "Lyfestyle", initials: "LY", monthlyRevenue: 0, assignedEditor: "e1", assignedSocialManager: "sm1", week: 2, status: "active" },
  { id: "c20", name: "Asadero", initials: "AS", monthlyRevenue: 0, assignedEditor: "e1", assignedSocialManager: "sm1", week: 3, status: "active" },
  { id: "c21", name: "Kinya Linden", initials: "KL", monthlyRevenue: 0, assignedEditor: "e1", assignedSocialManager: "sm1", week: 4, status: "active" },
  /* Javier's client */
  { id: "c22", name: "Sculpt Fitness", initials: "SF", monthlyRevenue: 0, assignedEditor: "e6", assignedSocialManager: "sm1", week: 1, status: "active" },
  /* Leonardo's client */
  { id: "c23", name: "Black Moon", initials: "BM", monthlyRevenue: 0, assignedEditor: "e3", assignedSocialManager: "sm1", week: 1, status: "active" },
];

/* ─── Videos (empty — Santiago will fill in) ─── */
export const INIT_VIDEOS: Video[] = [];

/* ─── Sales Leads (empty — Santiago will fill in) ─── */
export const INIT_LEADS: Lead[] = [];

/* ─── Onboarding (empty) ─── */
export const INIT_ONBOARDING: OnboardingClient[] = [];

/* ─── Ads (empty — Santiago will fill in) ─── */
export const INIT_ADS: AdCampaign[] = [];

/* ─── Knowledge Base ─── */
export const KB_CATEGORIES = ["SOPs", "Content Pipeline", "Editing", "Publishing", "Client Management", "Paid Advertising", "Social Media"];

export const KB_DOCS: KBDoc[] = [
  { id: "kb1", category: "Content Pipeline", title: "5-stage pipeline overview", author: "Jenina", updated: "2026-03-28", body: "Every piece of content follows five stages:\n\n1. Shoot -- Footage is captured on the scheduled shoot date.\n2. Edit -- Assigned editor produces the final cut.\n3. Internal Approval -- Creative Director or owner signs off.\n4. Sent to Guido -- Approved content enters the publishing queue.\n5. Posted -- Content goes live on the scheduled platform.\n\nNo stage can be skipped. Content must be approved before it reaches publishing. Publishing must be scheduled at least 7 days ahead of the post date." },
  { id: "kb2", category: "Editing", title: "Editor weekly capacity rules", author: "Jenina", updated: "2026-03-28", body: "Weekly target: 86 videos across all editors.\n\nIndividual caps:\n- Alex: 22 videos/week\n- Araceli: 22 videos/week\n- Sergio: 20 videos/week\n- Rodrigo: 20 videos/week\n- Javier: 22 videos/week\n- Leonardo: 22 videos/week\n- Santi: 22 videos/week\n\nIf an editor hits their cap, no additional videos can be assigned until the following week.\n\nRevision policy: 1 revision round included per video. A second revision triggers a warning and must be approved by the Creative Director." },
  { id: "kb3", category: "Publishing", title: "Guido publishing rules", author: "Jenina", updated: "2026-03-28", body: "Content must always be scheduled 7 days ahead of the post date. No same-day posting from fresh edits.\n\nBefore scheduling, every video must have:\n- Caption written and reviewed\n- Thumbnail created\n- Platform selected\n- Scheduled date confirmed\n\nGuido should be scheduling content every day. If the queue runs dry, escalate immediately." },
  { id: "kb4", category: "Content Pipeline", title: "Shoot scheduling rules", author: "Jenina", updated: "2026-03-28", body: "Max 6 client shoots per week. No exceptions.\n\nShoots are locked 60 days in advance. Canceled shoots cannot be replaced in the same week.\n\nEach client has a permanent week assignment (Week 1 through Week 4). Shoot dates follow the client week." },
  { id: "kb5", category: "Client Management", title: "New client onboarding checklist", author: "Jenina", updated: "2026-03-25", body: "A new client cannot enter production until all six steps are complete:\n\n1. Contract signed\n2. Invoice paid\n3. Strategy call completed\n4. Shoot date scheduled\n5. Editor assigned\n6. Social manager assigned\n\nNo exceptions. The system enforces this gate. If a step is missing, the Move to Production button stays locked." },
  { id: "kb6", category: "Paid Advertising", title: "Ads management process", author: "Jenina", updated: "2026-03-22", body: "Every client running ads must have a visible record in the Ads board showing:\n- Campaign name and platform\n- Status (active, paused, draft, ended)\n- Budget and spend\n- Creative being used\n- Optimization schedule\n\nOptimization reviews happen on the schedule set for each campaign. No campaign should run more than 2 weeks without a review." },
  { id: "kb7", category: "Social Media", title: "Caption writing framework", author: "Jenina", updated: "2026-03-20", body: "The Hook-Story-CTA Formula\n\nStep 1: The Hook (First Line)\nThis is the only line people see before tapping more. Make it count.\n- Ask a provocative question\n- Lead with a bold stat or claim\n- Start mid-story\n\nStep 2: The Story (Body)\nExpand on the hook with 3 to 5 lines of value. Use short paragraphs and line breaks.\n\nStep 3: The CTA (Last Line)\nTell them exactly what to do: save, share, comment, click link in bio.\n\nPlatform notes:\n- Instagram: 2,200 char max. Front-load value.\n- TikTok: Keep it under 150 chars. Punchy.\n- LinkedIn: Professional tone. Can go longer.\n- Facebook: 1 to 2 sentences. Direct and clear." },

  /* ─── SOPs ─── */
  { id: "kb-sop-editor", category: "SOPs", title: "SOP: Editor", author: "Jenina", updated: "2026-03-31", body: "STANDARD OPERATING PROCEDURE -- EDITOR\n\nRole: Produce final video edits on time and within revision limits.\n\nDaily Workflow:\n1. Log in to Agency OS and go to Production.\n2. Check your assigned videos for the current week.\n3. For each video in your queue:\n   a. Confirm footage is uploaded (checkbox must be checked).\n   b. If footage is missing, flag it immediately -- do not wait.\n   c. Begin editing and set status to \"Editing\".\n4. When the edit is complete, set status to \"Delivered\".\n5. The video will automatically appear in Approvals for review.\n6. If a revision is requested, you will see the video back in your queue with status \"Revision\" and notes from the reviewer.\n7. Apply the requested changes and set status back to \"Delivered\".\n\nRevision Policy:\n- 1 revision round is included per video.\n- A second revision triggers a warning. The Creative Director must approve it.\n- If you disagree with a revision request, message the reviewer directly -- do not ignore it.\n\nCapacity:\n- Your weekly cap is shown on the Editors page.\n- Do not accept work beyond your cap. If you are overloaded, notify the Creative Director.\n- Check the Editors page to see your current load vs. capacity.\n\nQuality Standards:\n- Every video must match the client's brand guidelines.\n- Audio must be clean -- no background noise unless intentional.\n- Color grading must be consistent across all videos for the same client.\n- Captions/subtitles must be accurate if included.\n- Export at the correct resolution for the target platform.\n\nWhat NOT to Do:\n- Do not change a video's status to \"Approved\" -- only reviewers can do that.\n- Do not skip the \"Delivered\" step.\n- Do not work on videos assigned to other editors without approval.\n- Do not access Sales, Ads, Clients, or Onboarding pages -- these are admin-only." },

  { id: "kb-sop-social", category: "SOPs", title: "SOP: Social Media Manager", author: "Jenina", updated: "2026-03-31", body: "STANDARD OPERATING PROCEDURE -- SOCIAL MEDIA MANAGER (GUIDO)\n\nRole: Schedule and publish all approved content across platforms.\n\nDaily Workflow:\n1. Log in to Agency OS and go to Publishing.\n2. Review all videos in the publishing queue (approved + sent to Guido).\n3. For each video:\n   a. Confirm caption is written -- toggle \"Caption\" to Done.\n   b. Confirm thumbnail is created -- toggle \"Thumbnail\" to Done.\n   c. Select all target platforms (Instagram, TikTok, Facebook, YouTube).\n   d. Set the scheduled date -- must be at least 7 days from today.\n   e. Change posting status to \"Scheduled\".\n4. On the scheduled date, publish the content on each platform.\n5. After publishing, change posting status to \"Posted\".\n\nCaption Writing:\n- Follow the Hook-Story-CTA framework (see Knowledge Base).\n- Instagram: up to 2,200 chars, front-load value.\n- TikTok: keep under 150 chars, punchy.\n- Facebook: 1-2 sentences, direct.\n- YouTube: include keywords for SEO in title and description.\n\nScheduling Rules:\n- Content must be scheduled at least 7 days ahead. No same-day posting.\n- Schedule content every day. If the queue runs dry, escalate to the Creative Director immediately.\n- Check the Calendar page for an overview of upcoming publish dates.\n\nPlatform-Specific Notes:\n- Instagram: Post Reels and carousels. Stories for BTS content.\n- TikTok: Prioritize trending audio. First 3 seconds must hook.\n- Facebook: Cross-post from Instagram when appropriate.\n- YouTube: Shorts for repurposed content. Long-form for tutorials/testimonials.\n\nWhat NOT to Do:\n- Do not publish content that hasn't been approved in the Approvals page.\n- Do not skip the caption or thumbnail step.\n- Do not schedule content for the same day it was approved.\n- Do not change video editing statuses -- that's the editor's job." },

  { id: "kb-sop-videographer", category: "SOPs", title: "SOP: Videographer", author: "Jenina", updated: "2026-03-31", body: "STANDARD OPERATING PROCEDURE -- VIDEOGRAPHER (SERGIO)\n\nRole: Capture footage on shoot days and upload to the production pipeline. Also edits assigned videos.\n\nShoot Day Workflow:\n1. Check the Calendar and Production pages for scheduled shoots.\n2. Confirm equipment is ready the day before:\n   - Camera, lenses, batteries charged\n   - Audio equipment (lav mic, shotgun mic)\n   - Lighting kit if indoor shoot\n   - Memory cards formatted\n3. Arrive at the client location on time. No exceptions.\n4. Capture all required footage per the shoot brief:\n   - B-roll of the business (interior, exterior, product, process)\n   - Talking head / testimonial if planned\n   - Action shots for Reels/TikTok\n   - Multiple angles for flexibility in editing\n5. After the shoot, upload all footage the same day.\n6. In Production, check the \"Footage Uploaded\" checkbox for each video.\n\nEditing (Dual Role):\n- Sergio also edits videos for assigned clients.\n- Follow the Editor SOP for all editing tasks.\n- Editing takes priority over re-shoots. Complete current edits before scheduling new shoots.\n\nShoot Scheduling Rules:\n- Max 6 client shoots per week across the agency.\n- Shoots are locked 60 days in advance.\n- Canceled shoots cannot be replaced in the same week.\n- Each client's shoot follows their permanent week assignment (Week 1-4).\n\nFootage Standards:\n- Shoot in 4K when possible (minimum 1080p).\n- Record audio separately when using a lav mic.\n- White balance must be set correctly for each location.\n- Capture at least 30 seconds of clean B-roll per setup.\n- Label all files clearly: ClientName_Date_ClipNumber.\n\nWhat NOT to Do:\n- Do not leave footage on memory cards overnight -- upload the same day.\n- Do not skip the \"Footage Uploaded\" checkbox. Editors are waiting on it.\n- Do not schedule shoots without confirming with the Creative Director.\n- Do not delete raw footage until the video has been approved and posted." },

  { id: "kb-sop-admin", category: "SOPs", title: "SOP: Admin (Santiago / Angel)", author: "Jenina", updated: "2026-03-31", body: "STANDARD OPERATING PROCEDURE -- ADMIN\n\nRole: Oversee all agency operations, manage clients and sales pipeline, make strategic decisions.\n\nDaily Check-In:\n1. Log in and review the Dashboard for key metrics:\n   - Active clients, MRR, videos this week, ad spend\n   - Pipeline health and conversion rate\n   - Bottleneck alerts (editors over capacity, content not scheduled ahead, stuck clients)\n2. Check Notifications for items needing attention.\n3. Review the Activity Log for recent changes across the workspace.\n\nSales Pipeline:\n1. Go to Sales to manage leads.\n2. Create new leads with all required info (contact, company, email, phone, source, estimated revenue).\n3. Move leads through stages: Lead > Call > Proposal > Follow Up > Closed Won / Closed Lost.\n4. When moving to \"Closed Won\":\n   - A confirmation popup will appear.\n   - An onboarding entry is auto-created.\n   - A celebration notification confirms the deal.\n5. Track conversion rates and pipeline value on the Dashboard.\n\nOnboarding:\n1. Go to Onboarding to manage new clients.\n2. Complete all 6 checklist steps:\n   - Contract signed\n   - Invoice paid\n   - Strategy call done\n   - Shoot scheduled\n   - Editor assigned (select from dropdown)\n   - Social manager assigned (select from dropdown)\n3. Set the package and fill in contact details.\n4. Once all steps are complete, select a week (1-4) and click \"Move to Production\".\n5. The client will appear in the Clients page and Production page.\n\nClient Management:\n1. Go to Clients to view all active clients.\n2. Edit package, revenue, week assignment, or status inline.\n3. Monitor for churned clients and update status.\n\nAds Management:\n1. Go to Ads to create and manage campaigns.\n2. Track budget, spend, and ROAS for each campaign.\n3. Review and optimize on the schedule set for each campaign.\n4. Pause underperforming campaigns. Scale winners.\n\nUser Management (Jenina only):\n1. Go to Users to add, edit, or remove team members.\n2. Set roles and board-level permissions.\n3. Only admins (Jenina, Angel, Santiago) can delete entries across the app.\n\nWeekly Review:\n- Review editor workload on the Editors page.\n- Click \"Suggest Rebalance\" if any editor is over capacity.\n- Check that all approved videos are scheduled in Publishing.\n- Export reports from Dashboard as needed (CSV).\n\nWhat NOT to Do:\n- Do not delete entries unless absolutely necessary -- deletions are logged.\n- Do not reassign editors without checking their current capacity.\n- Do not skip the onboarding checklist -- all 6 steps are enforced.\n- Do not change video editing statuses directly -- let editors and reviewers handle the pipeline." },
];
